# Generated by Django 3.2.8 on 2021-10-13 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoHiscar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileHash', models.CharField(default='', max_length=33, unique=True)),
                ('archivo', models.FilePathField(null=True, path='hiscar/')),
                ('peso', models.BigIntegerField()),
                ('cant_lineas', models.IntegerField(blank=True, default=None, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('split', models.BooleanField(default=False)),
                ('parsed', models.BooleanField(default=False, null=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_cargador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
