# Generated by Django 3.2.8 on 2021-10-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivohiscar',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
