# Generated by Django 3.2.7 on 2021-11-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivo', '0003_auto_20211013_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivohiscar',
            name='archivo',
            field=models.FilePathField(null=True, path='hiscar/'),
        ),
        migrations.AlterField(
            model_name='archivohiscar',
            name='upload',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
