# Generated by Django 3.2.7 on 2021-11-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivo', '0004_auto_20211109_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivohiscar',
            name='upload',
        ),
        migrations.AlterField(
            model_name='archivohiscar',
            name='archivo',
            field=models.FilePathField(null=True, path='media/'),
        ),
    ]
