# Generated by Django 3.2.7 on 2021-11-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivo', '0006_codigolargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivohiscar',
            name='parsed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
