# Generated by Django 3.2.7 on 2021-11-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archivo', '0007_archivohiscar_parsed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=6)),
                ('nombre', models.CharField(db_index=True, max_length=500)),
                ('has_modulo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'reparticiones',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=15)),
                ('cargo', models.CharField(db_index=True, max_length=200)),
                ('reparticion', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Cargo_reparticion', to='archivo.reparticion')),
            ],
        ),
        migrations.CreateModel(
            name='Hiscar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(db_index=True, default=None, null=True)),
                ('cargo', models.CharField(db_index=True, max_length=11)),
                ('reparticion', models.CharField(blank=True, db_index=True, default=None, max_length=4, null=True)),
                ('basico', models.DecimalField(decimal_places=2, max_digits=18)),
                ('suplemento1', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('suplemento2', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('antiguedad', models.TextField(default=None, null=True)),
                ('sumafija1', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sumafija2', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sumafija3', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cargo_obj', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cargo_objecto', to='archivo.cargo')),
                ('reparticion_obj', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Reparticion_objecto', to='archivo.reparticion')),
            ],
            options={
                'db_table': 'hiscars',
                'unique_together': {('periodo', 'cargo', 'reparticion')},
            },
        ),
    ]
