# Generated by Django 3.2.9 on 2021-11-15 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0010_remove_duplicate_indices'),
        ('archivo', '0009_alter_archivohiscar_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivo.archivohiscar')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_celery_results.taskresult')),
            ],
        ),
        migrations.AddField(
            model_name='archivohiscar',
            name='task',
            field=models.ManyToManyField(related_name='task_result', through='archivo.ArchivoTask', to='django_celery_results.TaskResult'),
        ),
    ]
